name: base
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - bwidget=1.9.11
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.14.12
  - certifi=2019.11.28
  - cftime=1.0.4.2
  - curl=7.67.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.63.1
  - graphite2=1.3.13
  - gsl=2.4
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=58.2
  - jpeg=9c
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.67.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libnetcdf=4.7.3
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libuv=1.26.0
  - libxml2=2.9.9
  - make=4.2.1
  - ncurses=6.1
  - netcdf4=1.5.3
  - numpy=1.17.3
  - openssl=1.1.1d
  - pango=1.42.4
  - pcre=8.43
  - pip=19.3.1
  - pixman=0.38.0
  - python=3.7.3
  - r-askpass=1.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-callr=3.2.0
  - r-checkmate=1.9.1
  - r-cli=1.1.0
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-desc=1.2.0
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-ggplot2=3.1.1
  - r-glue=1.3.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-htmltools=0.3.6
  - r-httpuv=1.5.2
  - r-igraph=1.2.4.2
  - r-inline=0.3.15
  - r-irdisplay=0.7.0
  - r-irkernel=0.8.15
  - r-jsonlite=1.6
  - r-labeling=0.3
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-lazyeval=0.2.2
  - r-loo=2.1.0
  - r-magrittr=1.5
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-matrixstats=0.54.0
  - r-mgcv=1.8_28
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-openssl=1.3
  - r-pbdzmq=0.3_3
  - r-pillar=1.3.1
  - r-pkgbuild=1.0.3
  - r-pkgconfig=2.0.2
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-promises=1.0.1
  - r-ps=1.3.0
  - r-r6=2.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcppeigen=0.3.3.5.0
  - r-repr=0.19.2
  - r-reshape2=1.4.3
  - r-rlang=0.3.4
  - r-rprojroot=1.3_2
  - r-rstan=2.18.2
  - r-scales=1.0.0
  - r-stanheaders=2.18.1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-sys=3.2
  - r-tibble=2.1.1
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-viridislite=0.3.0
  - r-withr=2.1.2
  - readline=7.0
  - setuptools=44.0.0
  - sqlite=3.28.0
  - tk=8.6.8
  - tktable=2.10
  - wheel=0.33.6
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.3.7
